### ISSUE TITLE
Reviews not displaying usernames

### ISSUE THREAD

**Issue by rconc016** [rconc016/CEN4010-TeamProject#69]
The book details review (or comments) section is not correctly displaying the usernames.

**Comment by tehSieghart** [comment]
Turns out there was no issue with either frontend or backend with displaying usernames. The problem was that the reviews that were all present in the database were attributed to a userId that doesn't have a user collection entry and thus none of the attributes we've created for our users in the user collection. Presumably, it was an old account created prior to the user service being finished. Either way I changed the userId to a valid one and the names and nicknames show up just fine.
